version: '3'

services:

  postgres:
    image: postgres
    container_name: pgsql-dev
    networks: 
      - redarc
    environment:
      POSTGRES_PASSWORD: test1234
    volumes:
      - pgredarc01:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h",  "pgsql-dev", "-U", "postgres"]
      timeout: 10s
      retries: 10

  redarc:
    build:
      context: .
      dockerfile: Dockerfile
    image: redarc
    container_name: redarc
    networks:
      - redarc
    environment:
      REDARC_API: http://redarc.mysite.org/api/
      REDARC_SUBMIT: http://redarc.mysite.org/submit/
      SERVER_NAME: redarc.mysite.org
      PGPASSWORD: test1234
      ES_ENABLED: 'true'
      # Do not change ES_HOST if elastichost is running on the same machine
      ES_HOST: http://es01:9200
      ES_PASSWORD: estest1234
      ADMIN_PASSWORD: "qwerty"
    ports:
      - "80:80"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: es01
    networks:
      - redarc
    environment:
      - discovery.type=single-node
      - ELASTIC_PASSWORD=estest1234
      # Change memory values
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    volumes:
      - esredarc01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: curl -s http://es01:9200 >/dev/null || exit 1
      timeout: 10s
      retries: 10

  redarc_ingest:
    build:
      context: ./redarc_ingest
      dockerfile: Dockerfile
    image: redarc_ingest
    container_name: redarc_ingest
    networks:
      - redarc
    environment:
      INGEST_ENABLED: true
      PG_DATABASE: postgres
      PG_USER: postgres
      PG_PASSWORD: test1234
      PG_HOST: pg-sql
      PG_PORT: 5432
      ES_ENABLED: true
      # Reddit credentials
      CLIENT_ID: change me
      CLIENT_SECRET: change me
      PASSWORD: change me
      USER_AGENT: "my user agent"
      REDDIT_USERNAME: "change me"
      INDEX_DELAY: 300
      INGEST_PASSWORD: asdf
    volumes:
      - redarc_ingest_logs:/ingest/logs
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

networks:
  redarc:
    driver: bridge
    name: redarc

volumes:
  pgredarc01:
    driver: local
  esredarc01:
    driver: local
  redarc_ingest_logs:
    driver: local